version: '2'
services:

    etcd1:
        extends:
            file: base.yml
            service: etcd-base
        ports:
             - "${ETCD1_ADVERTISE_PORT}:2379"
             - "${ETCD1_LISTEN_PORT}:2380"
        environment:
            ETCD_NAME: node1
            ETCD_DATA_DIR: "${DOCKER_ETCD_DATA_PATH}/etcd1.etcd"
            ETCD_INITIAL_ADVERTISE_PEER_URLS: "${ETCD1_SERVER_IP}:${ETCD1_LISTEN_PORT}"
            ETCD_ADVERTISE_CLIENT_URLS: "${ETCD1_SERVER_IP}:${ETCD1_ADVERTISE_PORT}"
            ETCD_PEER_CERT_FILE: "${DOCKER_ETCD_CERTS_PATH}/etcd1.pem"
            ETCD_PEER_KEY_FILE: "${DOCKER_ETCD_CERTS_PATH}/etcd1-key.pem"
    etcd2:
        extends:
            file: base.yml
            service: etcd-base
        ports:
            - "${ETCD2_ADVERTISE_PORT}:2379"
            - "${ETCD2_LISTEN_PORT}:2380"
        environment:
            ETCD_NAME: node2
            ETCD_DATA_DIR: "${DOCKER_ETCD_DATA_PATH}/etcd2.etcd"
            ETCD_INITIAL_ADVERTISE_PEER_URLS: "${ETCD2_SERVER_IP}:${ETCD2_LISTEN_PORT}"
            ETCD_ADVERTISE_CLIENT_URLS: "${ETCD2_SERVER_IP}:${ETCD2_ADVERTISE_PORT}"
            ETCD_PEER_CERT_FILE: "${DOCKER_ETCD_CERTS_PATH}/etcd2.pem"
            ETCD_PEER_KEY_FILE: "${DOCKER_ETCD_CERTS_PATH}/etcd2-key.pem"
    etcd3:
        extends:
            file: base.yml
            service: etcd-base
        ports:
            - "${ETCD3_ADVERTISE_PORT}:2379"
            - "${ETCD3_LISTEN_PORT}:2380"
        environment:
            ETCD_NAME: node3
            ETCD_DATA_DIR: "${DOCKER_ETCD_DATA_PATH}/etcd3.etcd"
            ETCD_INITIAL_ADVERTISE_PEER_URLS: "${ETCD3_SERVER_IP}:${ETCD3_LISTEN_PORT}"
            ETCD_ADVERTISE_CLIENT_URLS: "${ETCD3_SERVER_IP}:${ETCD3_ADVERTISE_PORT}"
            ETCD_PEER_CERT_FILE: "${DOCKER_ETCD_CERTS_PATH}/etcd3.pem"
            ETCD_PEER_KEY_FILE: "${DOCKER_ETCD_CERTS_PATH}/etcd3-key.pem"